name: Run tests for the project
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
    - master
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '19'
          cache: maven

      - name: Display JDK Version
        run: java -version

      - name: Set up Chrome browser
        uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: chrome
          version: latest

      - name: Run Automated tests
        run: mvn -X clean test
